kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hub-of-hubs-managedclusterset-admin
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: "Team Hub of Hubs"
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: "Team Hub of Hubs Admins"
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccounts:acm-hub-of-hubs'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:managedclusterset:admin:hub-of-hubs
