kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hub-of-hubs-namespace-access
  namespace: acm-hub-of-hubs
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: "Team Hub of Hubs"
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: "Team Hub of Hubs Admins"
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 'system:serviceaccounts:acm-hub-of-hubs'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
